# Theme settings
# S<span style="opacity:0.95">h</span><span style="opacity:0.9">a</span><span style="opacity:0.85">d</span><span style="opacity:0.8">o</span><span style="opacity:0.75">w</span><span style="opacity:0.7">e</span><span style="opacity:0.65">n</span><span style="opacity:0.6">v</span>

doks:
  baseurl: https://asthma-guardian.github.io/
  color_theme: # Available themes: blue (default), green, purple, red and yellow
  header:
    logo:
      text: |
        Asthma Guardian <span style="opacity:0.70;font-size: 12px;">by Resmonics</span>
      image:
    nav:
      - item_name: Getting Started
        item_url: /getting-started
      - item_name: AG SDK
        item_url: /ag-sdk
      - item_name: Best Practices
        item_url: /best-practices
      - item_name: Trust
        item_url: /trust
      - item_name: Integration
        item_url: /integration
  footer:
    content:
      logo:
        text: |
          Asthma Guardian
        image:
      copyright: "&copy;2020 Resmonics"
    social_list:
      - network_name: github
        profile_url: 'https://github.com/Asthma-Guardian'
      - network_name: linkedin
        profile_url: 'https://linkedin.com/company/asthma-guardian'
  google_analytics:
    tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
  comments:
    disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
  sass_dir: ./doks-theme/_sass
  style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
